### ISSUE TITLE
How are you generating the kernels?

### ISSUE THREAD

**Issue by FigBug** [LnxPrgr3/crossfeed#3]
How are you generating the kernels? I'd like to add support for any sample rate. Is it possible to generate kernels at runtime? I though the designer might do it, but not really sure how to use it.

**Comment by LnxPrgr3** [comment]
Sorry about the delay!

The designer included here is hopelessly out of date—I'm cleaning up the experimental one that generated the current filters today and committing it, since it can hardly be called experimental now.

They are still built by an iterative designer, so I don't recommend generating them at runtime—it works at the rates I've tested, but I can't guarantee it won't do something broken for, say, 16KHz or 192kHz. It's common for audio systems to run at one of several fixed rates, with audio at other rates being resampled before playback. With my old Mac as an example:

![screen shot 2017-02-11 at 6 56 49 pm](https://cloud.githubusercontent.com/assets/255056/22859014/00fed2d2-f08c-11e6-8025-ac602b6124ee.png)

The included player runs the crossfeed after the system-provided resampler (if one is needed—with defaults and CD-rate audio, it isn't), and so cares about CoreAudio's playback samplerate but not the input file's samplerate.

But if you do need arbitrary samplerates, soon you should have the current designer as a starting point.

**Comment by FigBug** [comment]
Thanks. I'd probably stay with hard coded for standard sample rates and generate for uncommon. I have some bluetooth headphones that do some uncommon rates.

**Comment by LnxPrgr3** [comment]
Progress update:

The branch replace-designer contains the most recent filter kernel generator. It's been updated to take the samplerate from the command line, and to compute its own filter length based on that—no more modifying #defines!

Still not the most convenient thing to use for runtime generation since its output is text to stdout, but I need to clock in and do day job stuff. Shouldn't be too hard to modify to return an array and a length instead. Or I can get to it later!

**Comment by FigBug** [comment]
Awesome, thanks!
